apiVersion: v1
kind: Service
metadata:
  name: busybox
#  namespace: journaling
  annotations:
    prometheus.io/scrape: 'true'
spec:
#  clusterIP: None
#  type: NodePort
  selector:
    component: busybox-test
  ports:
  - port: 25
    name: smtp
    protocol: TCP
