apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  annotations:
    pod.beta.kubernetes.io/hostname: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
