apiVersion: v1
kind: PersistentVolume
metadata:
  name: busybox-pvc
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: fs-623ee1cb.efs.us-west-2.amazonaws.com
    path: /
