apiVersion: v1
kind: Pod
metadata:
  name: logstash
spec:
  containers:
  - image: logstash:latest
    name: logstash
#    command:
#    - '/docker-entrypoint.sh'
#    args:
#    - 'logstash'
#    - 'agent'
#    - '-f'
#    - '/config-dir/logstash.conf'
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: config
      mountPath: /config-dir
    - name: logs
      mountPath: /logs
  volumes:
  - hostPath:
      path: /mnt/docker/configuration
    name: config
  - hostPath:
      path: /mnt/docker/logs
    name: logs
