apiVersion: v1
kind: Service
metadata:
  name: admin-interface
spec:
  clusterIP: None
  selector:
    app: admin
    role: django
    tier: frontend
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 80
    name: http
    protocol: TCP


---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-interface
#  namespace: journaling
  # labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: postgres
  #   role: master
  #   tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels
  #     app: postgres
  #     role: master
  #     tire: backend
  template:
    metadata:
      labels:
        app: admin
        role: django
        tier: frontend
    spec:
      containers:
      - name: django
        image: cyrusmc/django
        ports:
        - containerPort: 8000
          name: web
          protocol: TCP
        env:
        - name: DATABASE_HOST
          value: psql-master.default
        - name: DATABASE_NAME
          value: accounts
        - name: DATABASE_USER
          value: read_only
        - name: DATABASE_PASS
          value: accounts
