apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxplus
  # labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: postgres
  #   role: master
  #   tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels
  #     app: postgres
  #     role: master
  #     tire: backend
  template:
    metadata:
      labels:
        role: nginxplus
        tier: frontend
    spec:
      containers:
      - name: "nginxplus"
        #image: "b.gcr.io/kuar/motorboat:0.0.1"
        image: "cyrusmc/nginxplus"
        #args:
        #  - "--api-server=kube-master-01.ost.smarshdev.com:8080"
        #  - "--nginx-server=localhost:80"
        #  - "--nginx-status-server=localhost:8080"
