apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxplus
  # labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: postgres
  #   role: master
  #   tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels
  #     app: postgres
  #     role: master
  #     tire: backend
  template:
    metadata:
      labels:
        role: nginxplus
        tier: frontend
    spec:
      containers:
      - name: "nginxplus"
        image: "cyrusmc/nginxplus"
        ports:
          - name: http
            containerPort: 80
            hostPort: 80
          - name: http-alt
            containerPort: 8080
            hostPort: 8080
        volumeMounts:
          - mountPath: '/etc/nginx/conf.d'
            name: etc-nginx-confd
      volumes:
        - hostPath:
            path: '/etc/nginx/conf.d'
          name: etc-nginx-confd
