apiVersion: v1                                                                                                                     
kind: Service
metadata:
  name: psql-db
#  namespace: journaling
spec:
  selector:
    app: postgres
    tier: backend
  ports:
  - name: pgbouncer
    protocol: TCP
    port: 6432
  - name: postgres
    protocol: TCP
    port: 5432

---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-slave
#  namespace: journaling
  # labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: postgres
  #   role: master
  #   tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels
  #     app: postgres
  #     role: master
  #     tire: backend
  template:
    metadata:
      labels:
        app: postgres
        role: slave
        tier: backend
    spec:
      containers:
      - name: psql-slave
        image: cyrusmc/postgres_slave
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        env:
        - name: POSTGRES_MASTER_SERVER
          value: psql-master.default
      - name: pgbouncer
        image: cyrusmc/pgbouncer
        ports:
        - containerPort: 6432
          name: pgbouncer
          protocol: TCP
        env:
        - name: PGBOUNCER_AUTH_TYPE
          value: plain
        - name: POSTGRES_DATABASE
          value: accounts
        - name: POSTGRES_USER
          value: read_only
        - name: POSTGRES_PASS
          value: accounts
