apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: matt-test
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        component: k8s-jnlp-slave
    spec:
      containers:
      - name: docker
        image: docker
        imagePullPolicy: Always
        command:
        - "/bin/sleep"
        - "600000"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
