apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
spec:
  selector:
    app: jenkins
    role: master
  type: NodePort
  ports:
  - port: 8080
    name: http
    protocol: TCP
  - port: 50000
    name: jnlp
    protocol: TCP
