apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  clusterIP: None
  selector:
    app: admin
    role: django
    tier: frontend
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 80
    name: http
    protocol: TCP
