apiVersion: v1
kind: Service
metadata:
  name: ingress
#  namespace: journaling
spec:
#  clusterIP: None
#  type: NodePort
  selector:
    app: exim-dovecot
    role: smtp
    tier: frontend
  ports:
  - port: 25
    name: smtp
    protocol: TCP
  - port: 143
    name: imap
    protocol: TCP
  externalIPs:
  - 10.200.18.34
  - 10.200.18.35
  - 10.200.18.36
