apiVersion: v1
kind: Service
metadata:
  name: monitoring-netdata
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "netdata"
spec:
  selector:
    role: monitoring
    tier: frontend
  ports:
  - port: 19999
    name: http
    protocol: TCP
  externalIPs:
  - 10.200.18.34
  - 10.200.18.35
  - 10.200.18.36
