apiVersion: v1
kind: Service
metadata:
  name: nginx
#  namespace: journaling
spec:
  selector:
    role: nginxplus
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  - port: 8080
    targetPort: 8080
    name: http-alt
    protocol: TCP
  externalIPs:
  - 10.200.3.128
  - 10.200.3.133
  - 10.200.3.134
