apiVersion: v1
kind: Service
metadata:
  name: psql-db
#  namespace: journaling
spec:
  selector:
    app: postgres
    tier: backend
  ports:
  - name: pgbouncer
    protocol: TCP
    port: 6432
  - name: postgres
    protocol: TCP
    port: 5432
