apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  clusterIP: None
  selector:
    app: exim-dovecot
    role: smtp
    tier: frontend
  ports:
  - port: 25
    name: smtp
    protocol: TCP
  - port: 143
    name: imap
    protocol: TCP
