# a headless server to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  ports:
  - port: 11211
    name: activemq
  clusterIP: None
  selector:
    app: activemq

---

apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: activemq
  annotations:
spec:
  serviceName: "activemq"
  replicas: 3
  template:
    metadata:
      labels:
        app: activemq
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: activemq
        image: cyrusmc/activemq
        env:
        - name: ROLE
          value: prr
        ports:
        - containerPort: 61616
          name: openwire
#        readinessProbe:
#          tcpSocket:
#            port: openwire
#          initialDelaySeconds: 5
#          timeoutSeconds: 5
        volumeMounts:
        - name: git-volume
          mountPath: /configuration
        - name: nfs-volume
          mountPath: /var/lib/activemq/data
      volumes:
      - name: git-volume
        gitRepo:
          repository: "https://pit-gitlab-01.smarshinc.com/TechOps/activeMQ_config.git"
          directory: git
      - name: nfs-volume
        nfs:
          path: '/vol/development/activemq/prr'
          server: 'dev-nanfs-01.smarshdev.com'
