apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxplus-rc
spec:
  replicas: 1
  selector:
    app: nginxplus
  template:
    metadata:
      labels:
        app: nginxplus
    spec:
      #      nodeSelector:
      #  role: nginxplus
      containers:
      - name: nginxplus
        image: "cyrusmc/nginxplus"
        ports:
          - name: http
            containerPort: 80
            hostPort: 80
          - name: smtp
            containerPort: 25
            hostPort: 25
          - name: http-alt
            containerPort: 8080
            hostPort: 8080
        volumeMounts:
          - mountPath: "/etc/nginx"
            name: etc-nginx
      volumes:
        - hostPath:
            path: "/etc/nginx"
          name: etc-nginx
