apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-master
  namespace: journaling
spec:
  replicas: 1
  selector:
    database: postgres
    version: 9.3.13
    role: master
  template:
    metadata:
      labels:
        database: postgres
        role: master
        version: 9.3.13
    spec:
      containers:
      - name: dbmaster
        image: postgres:9.3.13
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        env:
        - name: DB_NAME
          value: accounts
        - name: DB_PASS
          value: accounts
        - name: DB_USER
          value: read_only
        volumeMounts:
        - name: scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      - name: pgbouncer
        image: cyrusmc/pgbouncer
        ports:
        - containerPort: 6432
          name: pgbouncer
          protocol: TCP
        env:
        - name: POSTGRES_DATABASE
          value: accounts
      volumes:
      - name: scripts
        hostPath:
          path: /mnt/docker_volumes/database/master
